### ISSUE TITLE
get_route_to

### ISSUE THREAD

**Issue by pshemk** [napalm-automation/napalm-junos#156] opened 2017-05-29 21:02 UTC
### Description of Issue/Question
get_route_to doesn't let to specify a table. When multiple vpnv4 tables are present the resulting routes can not be parsed to valid ipv4 address:

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[X] Yes
[ ] No

### napalm-junos version
(Paste verbatim output from `pip freeze | grep napalm-junos` between quotes below)

```
napalm-junos==0.6.6 (also with current develop branch)
```

### JunOS version
(Paste verbatim output from `show version and haiku` between quotes below)

```
Model: mx10-t
Junos: 13.3R6-S2
JUNOS Base OS boot [13.3R6-S2]
JUNOS Base OS Software Suite [13.3R6-S2]
JUNOS Kernel Software Suite [13.3R6-S2]
JUNOS Crypto Software Suite [13.3R6-S2]
JUNOS Packet Forwarding Engine Support (MX80) [13.3R6-S2]
JUNOS Online Documentation [13.3R6-S2]
JUNOS Services Application Level Gateways [13.3R6-S2]
JUNOS Services Jflow Container package [13.3R6-S2]
JUNOS Services Stateful Firewall [13.3R6-S2]
JUNOS Services NAT [13.3R6-S2]
JUNOS Services RPM [13.3R6-S2]
JUNOS Services Crypto [13.3R6-S2]
JUNOS Services SSL [13.3R6-S2]
JUNOS Services IPSec [13.3R6-S2]
JUNOS Routing Software Suite [13.3R6-S2]
```

### Steps to Reproduce the Issue
Run the following playbook (using napalm-ansible):

```
- name: fetch info
  gather_facts: false
  hosts: all
  connection: local
  tasks:
    - name: get facts
      napalm_get_facts:
        hostname: "10.69.0.35"
        username: "******"
        password: "******"
        dev_os: "junos"
        filter:
          - "route_to"
        args:
          route_to:
           destination: 8.8.8.0/24
      register: result
    - name: display results
      debug: var=result

```
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
TASK [get facts] *****************************************************************************************************************************************************************************
fatal: [vsrx01]: FAILED! => {"changed": false, "failed": true, "msg": "[route_to] cannot retrieve device data: failed to detect a valid IP address from u'10.69.0.177:500:8.8.8.0'"}
        to retry, use: --limit @/home/ubuntu/2d-automation/ansible/getdata.retry
```

**Comment by mirceaulinic** [comment] 2017-05-30 08:33
Duplicate of https://github.com/napalm-automation/napalm-junos/issues/121

**Closed as completed by mirceaulinic** 2017-05-30 08:33 UTC
Labels: duplicate
